#!/usr/bin/env bash
set -eu -o pipefail

output=
TEST_PASSED=false
trap '  ec=$?
        $TEST_PASSED || echo "FAILURE: unexpected exit; code=$ec"
' 0

####################################################################

optargs=()
pactivate_test=true
pae_test=true
while [[ ${#@} -gt 0 ]]; do case "$1" in
    -e)     shift; pactivate_test=false;;
    -E)     shift; pae_test=false;;
    -*)     optargs+=("$1"); shift;;
    *)      break;;
esac; done
[[ ${#@} -eq 0 ]] && set debian:11 ubuntu:22.04     # default images to test

export PROJDIR=$(cd "$(dirname "$0")" && pwd -P)
cd "$PROJDIR"

header() {
    echo '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    echo '┃' "$@"
}

$pactivate_test && for img in "$@"; do
    header tscript/pactivate-test-docker
    ./tscript/pactivate-test-docker "${optargs[@]}" "$1"
done

$pae_test && {
    header tscript/pae-test
    ./tscript/pae-test "${optargs[@]}"
}

header "All tests passed"
    echo '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
TEST_PASSED=true
