#!/usr/bin/env bash
set -eu -o pipefail

export PROJDIR=$(cd "$(dirname "$0")/.." && pwd -P)

sudo=sudo; [[ -e $PROJDIR/.no-sudo ]] && sudo=
winpty=; msys_prefix=
[[ "${MSYSTEM:-}" =~ (MSYS|MINGW).* ]] && \
    { sudo=; winpty=winpty; msys_prefix=/; }

TEST_INTERACT=false     # `true` if we start an interactive shell in the
                        #   container after running the tests
TEST_QUIET=             # -q if we are running tests as quietly as possible

while [[ $# -gt 0 ]]; do case "$1" in
    -i)     shift; TEST_INTERACT=true;;
    -q)     shift; TEST_QUIET=-q;;
    *)      break;;
esac; done
if [[ $# -ne 1 ]]; then
    echo 1>&2 "$0: takes one arg, not: $@"; exit 2
else
    DISTRO="$1"
    IMG=pactivate_test:"${DISTRO/:/-}"  # name of image we build for testing
fi

cd "$PROJDIR"
[[ -n $sudo ]] && $sudo -v -p '[sudo] password for %p (to run docker): '

echo "From $DISTRO building $IMG (this may take a few moments)...."
$sudo docker build -f tscript/docker-data/Dockerfile \
    --build-arg=DISTRO="$DISTRO" \
    $TEST_QUIET -t "$IMG" .
$sudo $winpty docker run --rm -it \
    -e "TEST_INTERACT=$TEST_INTERACT" -e "TEST_QUIET=$TEST_QUIET" \
    "$IMG" $msys_prefix/test/cont-test
