#!/usr/bin/env bash
set -eu -o pipefail

output=
TEST_PASSED=false
trap '  ec=$?
        $TEST_PASSED || {
            echo "FAILURE: unexpected exit; code=$ec"
            echo -e  "Last output:\n  $output"
        }
' 0

fail() { echo -e FAILURE: "$@"; TEST_PASSED=true; exit 1; }

####################################################################
#   Setup

export PROJDIR=$(cd "$(dirname "$0")/.." && pwd -P)

TEST_QUIET=             # -q if we are running tests as quietly as possible
while [[ $# -gt 0 ]]; do case "$1" in
    -i)     shift;; # no interactive mode needed
    -q)     shift; TEST_QUIET=-q;;
    *)      echo 1>&2 "$0: Unknown argument: $1"; exit 2;;
esac; done

export PAE_HOME="$PROJDIR"/.build/test/pae
rm -rf "$PAE_HOME"; mkdir -p "$PAE_HOME"
. "$PROJDIR"/pae
cd /    # Ensure we're not dependent on CWD

####################################################################
#   Tests: arg errors, help, download

echo '━━━━━ no arguments error'
output=$(2>&1 pae) && fail "Accepted no args."
[[ $output =~ 'missing parameter'  ]] || fail "bad message:\n  $output"

echo '━━━━━ bad argument error'
output=$(2>&1 pae -Y) && fail "Accepted bad arg -Y."
[[ $output =~ 'bad option: -Y (-h for help)'  ]] \
    || fail "bad message:\n  $output"

echo '━━━━━ pae -h'
output=$(pae -h)
[[ $output =~ "Usage:"  ]] \
    || fail "bad message: $output"

echo '━━━━━ pae -D'
(   cd "$PAE_HOME"
    rm -f pactivate
    pae -D
    ls -l pactivate
    test -s pactivate
) || fail "Failed to download pactivate"

echo '━━━━━ pae nonexistent'
if output=$(2>&1 pae nonexistent); then
    fail 'Accepted nonexistent virtual env.'
else
    [[ $output =~ 'does not appear to be a virtual env' ]] \
        || fail "bad message:\n  $output"
fi

####################################################################
#   Tests: creation, listing, activation, run, removal

echo '━━━━━ pae -c te0'
#   To save time, -C is tested at the same time as -p, below.
pae -c te0
[[ -z ${VIRTUAL_ENV-} ]] || fail "-c should not have activated virtualenv"
[[ -r "$PAE_HOME"/te0/.build/virtualenv/pyvenv.cfg ]] || fail 'no pyenv.cfg'
[[ -r "$PAE_HOME"/te0/requirements.txt ]] \
    && fail "requirements.txt should not have been created"

echo '━━━━━ pae -l'
output=$(2>&1 pae -l)
[[ $output == 'te0' ]] || fail "bad listing:\n  $output"

echo '━━━━━ pae -a te0'
pae -a te0
[[ $(type python) =~ /te0/.build/virtualenv/bin/python$ ]] \
    || fail "Python at wrong path: $(type python)"

echo '━━━━━ pae -d'
pae -d
[[ $(type python 2>/dev/null) =~ /te0/.build/virtualenv ]] \
    && fail "Python at wrong path: $(type python)"

echo '━━━━━ pae -d # not activated'
output=$(2>&1 pae -d) || true
[[ $output =~ 'no deactivate()' ]] || fail "bad output:\n  $output"

echo '━━━━━ pae -r ...'
pae -r te0 pip install six || fail "run with environment name"
#   As well as testing with an environment name (above), we also test
#   with an explicit path. This includes multiple adjacent slashes and
#   trailing slashes while running `python` to surface the "multi-slash"
#   bug, if present. (See the fix of $vedir for this in the source.)
#   XXX Unfortunately, this doesn't seem to trigger the bug when the fix
#   isn't present.; only cjs has been able to reproduce it by hand.
(cd "$PAE_HOME" && pae .//te0// python -c 'import six') \
    || fail 'run with explicit dir and multiple slashes'

echo '━━━━━ pae --rm te0'
output=$(2>&1 pae --rm te0)
[[ -e "$PAE_HOME"/te0 ]] && fail 'environment not removed'

####################################################################
#   Tests: interpreter selection

echo '━━━━━ pae -p ... with nonexistent interpreter argument'
output=$(2>&1 pae -p /no/such/path -c te-p0) && fail "bad -p path not caught"
[[ $output =~ 'No such file' ]] || fail "bad output:\n  $output"

echo '━━━━━ pae -p ... with bad interpreter argument'
output=$(2>&1 pae -p /usr/bin/env -c te-p0) && fail "bad -p path not caught"
[[ $output =~ 'bad python interpreter: /usr/bin/env' ]] \
    || fail "bad output:\n  $output"

echo '━━━━━ pae -p ... -C te-p'
#   It's a lot of work to build a separate Python interpreter, but pactivate
#   using the .python link has already been tested, so we can simply verify
#   here that pae created the link. Note that we deliberately test without
#   a full path.
#   To save time, this also tests that -C activates the virtualenv and
#   requirements.txt creation.
pae -p python3 -C te-p1 six urllib3
[[ ${VIRTUAL_ENV-} =~ /te-p1/ ]] \
    || fail "-C did not activate virtualenv (VIRTUALENV='${VIRTUAL_ENV-}')"
rqtxt="$PAE_HOME"/te-p1/requirements.txt
[[ -r $rqtxt ]] || fail "requirements.txt not created"
grep -q 'six' "$rqtxt" || fail 'requirements.txt does not contain six'
grep -q 'urllib3' "$rqtxt" || fail 'requirements.txt does not contain urllib3'

pae -d
[[ -r "$PAE_HOME"/te-p1/.build/virtualenv/pyvenv.cfg ]] \
    || fail 'no pyenv.cfg'
[[ -L "$PAE_HOME"/te-p1/.python ]] || fail 'no .python link'
output=$(2>&1 pae --rm te-p1)
[[ -L "$PAE_HOME"/te-p1/.python ]] && fail '.python link not removed'

echo '━━━━━ TESTS COMPLETE'
TEST_PASSED=true
